// 14A Admin · AI Compliance Report — the regulator-ready deliverable.
// Everything is live from /api/report (KPIs, risk score, framework coverage,
// control mapping, masked evidence) and the executive summary is written by
// the Governance Copilot (Gemini when a key is set, deterministic analyst
// otherwise — labelled either way). "Download" produces a self-contained,
// print-ready HTML the org can hand to an auditor. Only masked records are
// ever included — no raw personal data leaves the platform.
import { useEffect, useState } from 'react'
import { api } from '../../lib/api.js'

const bandColor = { Low: '#058f6b', Moderate: '#d5a71f', Elevated: '#e0771b', High: '#db2629' }
const rm = n => 'RM ' + Number(n || 0).toLocaleString()

export default function AuditReport() {
  const [report, setReport] = useState(null)
  const [summary, setSummary] = useState(null)
  const [regen, setRegen] = useState(false)

  useEffect(() => {
    api.get('/report').then(setReport).catch(() => {})
    api.get('/report/summary').then(setSummary).catch(() => setSummary({ summary: '', source: 'offline' }))
  }, [])

  async function regenerate() {
    setRegen(true)
    try { setSummary(await api.get('/report/summary')) } catch { /* keep */ } finally { setRegen(false) }
  }

  const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  const risk = report?.risk
  const k = report?.kpis

  const kpiCards = k ? [
    [k.promptsProtected.toLocaleString(), 'Prompts protected'],
    [k.itemsMasked.toLocaleString(), 'Sensitive items masked'],
    [rm(k.valueProtected), 'Exposure value protected'],
    [k.toolsApproved, 'Tools reviewed & approved'],
    [k.risksResolved, 'Risks resolved'],
    [k.confirmedLeaks, 'Confirmed data leaks'],
  ] : []

  function download() {
    if (!report) return
    const fw = report.frameworks.map(f => `<tr><td>${f.name}</td><td>${f.detail}</td><td style="color:#058f6b;font-weight:bold">${f.status}</td></tr>`).join('')
    const ctrl = report.controls.map(c => `<tr><td>${c.type}</td><td>${c.framework}</td><td>${c.evidence}</td></tr>`).join('')
    const kpiRows = kpiCards.map(([v, label]) => `<tr><td>${label}</td><td>${v}</td></tr>`).join('')
    const ev = report.topEvents.map(e => `<tr><td>${e.time}</td><td>${e.user}</td><td>${e.dept}</td><td>${e.tool}</td><td>${e.action}</td><td>${e.record}</td></tr>`).join('')
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>AI Passport — Compliance Report</title>
<style>body{font-family:Arial,Helvetica,sans-serif;margin:40px;color:#0a204f;max-width:900px}
h1{margin:2px 0}h2{color:#0a204f;margin-top:30px;border-bottom:2px solid #d9b32c;padding-bottom:5px}
.kick{color:#d9b32c;font-weight:bold;font-size:12px;letter-spacing:1px}
.risk{display:inline-block;background:${bandColor[risk.band]};color:#fff;font-weight:bold;padding:6px 16px;border-radius:20px;font-size:14px}
.sum{background:#f7f4ea;border-left:4px solid #d9b32c;padding:14px 18px;border-radius:6px;font-size:14px;line-height:1.6}
table{border-collapse:collapse;width:100%;font-size:12.5px;margin-top:10px}td,th{border:1px solid #e0e0e5;padding:7px 10px;text-align:left}
th{background:#0b2457;color:#d9b32c}.foot{margin-top:26px;font-size:11px;color:#667085}</style></head><body>
<p class="kick">AI GOVERNANCE — COMPLIANCE AUDIT REPORT</p>
<h1>${report.org}</h1><p>Reporting period ${report.period} · Generated ${today}</p>
<p style="margin-top:14px">Organisational AI Risk Score: <span class="risk">${risk.score}/100 · ${risk.band}</span></p>
<h2>Executive summary</h2><div class="sum">${(summary?.summary || '').replace(/</g, '&lt;')}</div>
<p style="font-size:11px;color:#667085">${summary?.source === 'gemini' ? 'Written by Gemini from live audit data.' : 'Generated by the governance analyst from live audit data.'}</p>
<h2>Framework coverage</h2><table><tr><th>Framework</th><th>Evidence</th><th>Status</th></tr>${fw}</table>
<h2>Control mapping</h2><table><tr><th>Data category</th><th>Framework control</th><th>Evidence</th></tr>${ctrl}</table>
<h2>Period summary</h2><table><tr><th>Metric</th><th>Value</th></tr>${kpiRows}</table>
<h2>Evidence — recent masked records</h2><table><tr><th>Time</th><th>User</th><th>Dept</th><th>Tool</th><th>Action</th><th>Stored (masked) record</th></tr>${ev}</table>
<p class="foot">Generated from the append-only audit log. Only masked records are included — no raw personal data leaves the platform. This document is suitable for internal governance review and regulator disclosure under Malaysia PDPA, the NIST AI RMF, and the EU AI Act.</p>
</body></html>`
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `aipassport-compliance-report-${new Date().toISOString().slice(0, 10)}.html`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div>
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-[30px] font-bold text-[#0a204f]">AI Compliance Report</h1>
          <p className="text-[#667085] text-sm mt-1.5">Live from the audit log · masked data only · regulator-ready. Generated {today}.</p>
        </div>
        <button onClick={download} disabled={!report} className="bg-gold-brand hover:bg-gold text-navy-header font-semibold text-sm w-[200px] h-12 rounded-full cursor-pointer disabled:opacity-60">
          Download report&nbsp;&nbsp;↓
        </button>
      </div>

      <div className="bg-white border border-[#e0e0e5] rounded-[16px] p-8 mt-6">
        <div className="flex items-start justify-between">
          <div>
            <p className="text-gold-brand font-bold text-xs">AI GOVERNANCE — COMPLIANCE AUDIT REPORT</p>
            <p className="text-[#0a204f] font-bold text-base mt-1.5">{report?.org || 'Example Sdn Bhd'} · Reporting period {report?.period || '1–22 Jul 2026'}</p>
          </div>
          {risk && (
            <div className="text-right shrink-0">
              <p className="text-[#8a7d56] font-semibold text-[10px]">AI RISK SCORE</p>
              <span className="inline-block text-white font-bold text-sm rounded-full px-4 py-1.5 mt-1" style={{ background: bandColor[risk.band] }}>
                {risk.score}/100 · {risk.band}
              </span>
            </div>
          )}
        </div>
        <div className="h-px bg-[#e5e5eb] mt-6" />

        {/* AI executive summary */}
        <div className="flex items-center justify-between mt-6">
          <p className="text-[#8a7d56] font-semibold text-[11px]">EXECUTIVE SUMMARY</p>
          <button onClick={regenerate} disabled={regen} className="text-[#365fd9] font-semibold text-[11px] cursor-pointer disabled:opacity-50">
            {regen ? 'Generating…' : '✦ Regenerate with AI'}
          </button>
        </div>
        <div className="bg-[#f7f4ea] border-l-4 border-gold-brand rounded-r-[10px] px-5 py-4 mt-2">
          {summary?.summary
            ? <p className="text-[#344054] text-[13.5px] leading-relaxed">{summary.summary}</p>
            : <p className="text-[#98a2b3] text-[13px]">Writing executive summary from live audit data…</p>}
          {summary?.summary && (
            <p className={`mt-2.5 text-[9px] font-semibold tracking-[0.5px] ${summary.source === 'gemini' ? 'text-[#365fd9]' : 'text-[#8a7d56]'}`}>
              {summary.source === 'gemini' ? '✦ WRITTEN BY GEMINI · FROM LIVE AUDIT DATA' : '◆ GOVERNANCE ANALYST · FROM LIVE AUDIT DATA'}
            </p>
          )}
        </div>

        {/* Framework coverage */}
        <p className="text-[#8a7d56] font-semibold text-[11px] mt-7">FRAMEWORK COVERAGE</p>
        <div className="flex flex-col gap-2.5 mt-3">
          {(report?.frameworks || []).map(f => (
            <div key={f.name} className="bg-[#e7f4ee] rounded-[10px] h-14 px-4.5 flex items-center gap-3">
              <span className="text-[#078b6c] font-bold text-base">✓</span>
              <div className="flex-1">
                <p className="text-[#0a204f] font-bold text-[15px]">{f.name}</p>
                <p className="text-[#667085] text-[13px]">{f.detail}</p>
              </div>
              <span className="bg-[#078b6c] text-white font-bold text-[11px] rounded-full px-3.5 h-[26px] flex items-center">{f.status.toUpperCase()}</span>
            </div>
          ))}
        </div>

        {/* Period summary */}
        <p className="text-[#8a7d56] font-semibold text-[11px] mt-7">PERIOD SUMMARY</p>
        <div className="grid grid-cols-3 gap-3.5 mt-3">
          {kpiCards.map(([v, label]) => (
            <div key={label} className="bg-[#fafafc] border border-[#e5e5eb] rounded-[10px] px-4.5 py-3.5">
              <p className="text-[#0a204f] font-bold text-[24px]">{v}</p>
              <p className="text-[#667085] text-[13px] mt-1">{label}</p>
            </div>
          ))}
        </div>

        {/* Control mapping */}
        <p className="text-[#8a7d56] font-semibold text-[11px] mt-7">CONTROL MAPPING — WHAT WE PROTECT AND WHY</p>
        <div className="border border-[#e5e5eb] rounded-[10px] overflow-hidden mt-3">
          <div className="grid grid-cols-[1.4fr_1.2fr_1.4fr] bg-navy-header text-gold-brand font-semibold text-[10px] tracking-[0.5px] px-4 py-2.5">
            <p>DATA CATEGORY</p><p>FRAMEWORK CONTROL</p><p>EVIDENCE</p>
          </div>
          {(report?.controls || []).map((c, i) => (
            <div key={c.type} className={`grid grid-cols-[1.4fr_1.2fr_1.4fr] px-4 py-3 text-[11.5px] ${i % 2 ? 'bg-white' : 'bg-[#fcfaf3]'}`}>
              <p className="text-[#0a204f] font-medium pr-2">{c.type}</p>
              <p className="text-[#475467] pr-2">{c.framework}</p>
              <p className="text-[#667085]">{c.evidence}</p>
            </div>
          ))}
        </div>

        <p className="text-[#667085] text-[12.5px] mt-7">
          This report is generated from the append-only audit log. Only masked records are included — no raw personal data leaves the platform.
        </p>
      </div>
    </div>
  )
}
